#!/usr/bin/env python3
"""Generate .env.example and docs/configuration.md from the settings inventory.

Hand-maintained configuration docs drift the moment someone adds a setting.
These are generated from ``app.settings.FIELDS`` — the same table the
application validates against — and CI re-runs this and fails if the committed
files differ, so documentation cannot silently fall behind the code.

    python3 tools/gen_config_docs.py           # write
    python3 tools/gen_config_docs.py --check   # verify, exit 1 on drift
"""
from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "backend"))

from app.settings import FIELDS, MIN_SECRET_LENGTH  # noqa: E402

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")

GROUPS = [
    ("Storage", ["DATA_DIR", "DATABASE_URL", "USE_SHARED_POSTGRES",
                 "POSTGRES_PROVISION_TOKEN"]),
    ("Security", ["SECRET_KEY", "JWT_HOURS", "DISABLE_AUTH", "ALLOW_REGISTRATION"]),
    ("Network & proxy", ["PORT", "CORS_ORIGINS", "TRUSTED_PROXY_COUNT"]),
    ("AI providers", ["AI_PROVIDER", "ANTHROPIC_API_KEY", "CLAUDE_MODEL",
                      "OPENAI_API_KEY", "OPENAI_MODEL", "OPENAI_BASE_URL",
                      "OLLAMA_HOST", "OLLAMA_MODEL", "AI_TIMEOUT_SECONDS"]),
    ("MCP (Home Assistant Assist)", ["MCP_ENABLED", "MCP_HOST", "MCP_PORT",
                                     "MCP_API", "MCP_API_TOKEN", "MCP_SERVER_TOKEN", "MCP_REQUIRED"]),
    ("Edibl integration (companion inventory app)", ["EDIBL_URL", "EDIBL_API_TOKEN"]),
    ("Serving", ["WORKERS", "THREADS", "TIMEOUT", "GRACEFUL_TIMEOUT",
                 "MAX_UPLOAD_MB", "HTTP_TIMEOUT_SECONDS", "MAX_IMPORT_BYTES"]),
    ("Misc", ["FRONTEND_DIST", "LOG_LEVEL", "DEBUG"]),
]


def _shown_default(f) -> str:
    if isinstance(f.default, tuple):
        return ",".join(f.default)
    if isinstance(f.default, bool):
        return "true" if f.default else "false"
    return str(f.default)


def render_env_example() -> str:
    out = [
        "# myMeal configuration — EXAMPLE ONLY.",
        "#",
        "# Copy to .env and edit. Every value here is a placeholder: this file",
        "# contains NO usable secrets and is safe to commit.",
        "#",
        "# Generated by tools/gen_config_docs.py from the settings inventory.",
        "# Do not edit by hand — CI regenerates and diffs it.",
        "#",
        "# Full reference, including security impact: docs/configuration.md",
        "",
    ]
    by_name = {f.name: f for f in FIELDS}
    for title, names in GROUPS:
        out.append(f"# --- {title} " + "-" * max(0, 62 - len(title)))
        for name in names:
            f = by_name[name]
            for line in _wrap(f.doc, 74):
                out.append(f"# {line}")
            if f.secret:
                out.append(f"# SECRET. Also supported: {f.env_var}_FILE=/run/secrets/... "
                           "(Docker secrets)")
            out.append(f"#{f.env_var}={_shown_default(f)}")
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def _wrap(text: str, width: int) -> list[str]:
    words, lines, cur = text.split(), [], ""
    for w in words:
        if len(cur) + len(w) + 1 > width:
            lines.append(cur)
            cur = w
        else:
            cur = f"{cur} {w}".strip()
    if cur:
        lines.append(cur)
    return lines


def render_reference() -> str:
    by_name = {f.name: f for f in FIELDS}
    out = [
        "# Configuration reference",
        "",
        "<!-- Generated by tools/gen_config_docs.py — do not edit by hand. -->",
        "",
        "Every setting myMeal understands. This table is generated from the same",
        "inventory the application validates against, so it cannot drift.",
        "",
        "## Precedence",
        "",
        "Highest wins:",
        "",
        "1. **Explicit config** passed to `create_app()` (tests, embedding).",
        "2. **Home Assistant add-on options** (`/data/options.json`).",
        "3. **Environment variables** (`MYMEAL_*`, or `MYMEAL_*_FILE` for secrets).",
        "4. **Built-in defaults.**",
        "",
        "Home Assistant options outrank the environment because, inside the add-on,",
        "options.json is the only surface an operator can edit — if the environment",
        "won, toggling a switch in the HA UI would silently do nothing. Outside Home",
        "Assistant the file does not exist, so the environment is authoritative.",
        "",
        "An empty environment variable (`MYMEAL_AI_PROVIDER=`) means *unset*, and",
        "falls through to the default rather than failing validation.",
        "",
        "## Validation",
        "",
        "Configuration is validated once at startup, before the database is opened",
        "and before any port is bound. Invalid configuration prints **every** problem",
        "and refuses to start — it never surfaces later as a request-time 500.",
        "",
        "Booleans accept `1 true yes on` / `0 false no off` (any case). Anything else",
        "is an error: an unrecognised value is never silently treated as false.",
        "",
        "Check a deployment without starting it:",
        "",
        "```bash",
        "docker compose run --rm app python3 -m app.config_check",
        "```",
        "",
        "## Settings",
        "",
    ]
    for title, names in GROUPS:
        out += [f"### {title}", "",
                "| Variable | Type | Default | Secret | Restart | Notes |",
                "|---|---|---|---|---|---|"]
        for name in names:
            f = by_name[name]
            typ = getattr(f.parse, "__name__", "str")
            typ = {"parse": "enum/int", "as_str": "string", "parse_bool": "boolean",
                   "http_url": "url", "csv_list": "list"}.get(typ, typ)
            default = _shown_default(f) or "_(empty)_"
            note = f.doc.replace("|", "/")
            if f.ha_option:
                note += f" HA option: `{f.ha_option}`."
            if f.supports_file:
                note += f" Supports `{f.env_var}_FILE`."
            out.append(
                f"| `{f.env_var}` | {typ} | `{default}` | "
                f"{'**yes**' if f.secret else 'no'} | "
                f"{'yes' if f.restart_required else 'no'} | {note} |"
            )
        out.append("")

    out += [
        "## Security notes",
        "",
        f"- **`MYMEAL_SECRET_KEY`** must be at least {MIN_SECRET_LENGTH} characters when",
        "  authentication is enabled, and known placeholders are rejected outright.",
        "  Leave it unset and myMeal generates one **once** and persists it to",
        "  `$MYMEAL_DATA_DIR/.secret_key` (mode 0600). Back that file up with your",
        "  data: losing it logs everyone out and voids every issued API token.",
        "- **`MYMEAL_DISABLE_AUTH=true` binds every request to one local user.** It is",
        "  correct behind Home Assistant ingress and wrong anywhere else. Combining it",
        "  with `MYMEAL_CORS_ORIGINS` is refused outright, because that would let any",
        "  listed website drive the API as that user.",
        "- **CORS is same-origin by default.** The SPA is served by the app itself, so",
        "  no cross-origin access is needed. Only add origins for a separate frontend",
        "  (e.g. the Vite dev server at `http://localhost:5173`). `*` is refused.",
        "- **`X-Forwarded-*` headers are ignored** unless `MYMEAL_TRUSTED_PROXY_COUNT`",
        "  is set, since anyone can send them.",
        "- **Secrets never reach the frontend.** Provider keys are used server-side",
        "  only, and are redacted from logs, `config_check`, and error messages.",
        "",
        "## Deployment support",
        "",
        "| Setting group | Standalone Docker | Home Assistant add-on |",
        "|---|---|---|",
        "| Storage | yes (mount a volume) | fixed to `/data`, backed up by HA |",
        "| Security | yes | `disable_auth` / `allow_registration` via add-on options |",
        "| AI providers | yes | `ai_provider` via add-on options; keys in the app UI |",
        "| MCP | yes | `enable_mcp` via add-on options |",
        "| Serving | yes | yes (environment) |",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    targets = {
        os.path.join(ROOT, ".env.example"): render_env_example(),
        os.path.join(ROOT, "docs", "configuration.md"): render_reference(),
    }
    drift = []
    for path, content in targets.items():
        if args.check:
            current = open(path).read() if os.path.exists(path) else None
            if current != content:
                drift.append(os.path.relpath(path, ROOT))
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w") as fh:
                fh.write(content)
            print(f"  wrote {os.path.relpath(path, ROOT)}")

    if drift:
        print("Configuration docs are out of date: " + ", ".join(drift))
        print("Regenerate with: python3 tools/gen_config_docs.py")
        return 1
    if args.check:
        print("Configuration docs are up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
